apiVersion: v1
kind: ConfigMap
metadata:
  name: middleware-server
  namespace: services
  labels:
    app: middleware-server
data:
  application-k8s.yaml: |
    hello:
      backend:
        url: http://backend-service.services/hello
