management:
  endpoint:
    health:
      probes:
        enabled: true
hello:
  backend:
    url: http://localhost:8081/hello
logging:
  level:
    de.qaware.security.lab.oidc.middleware.server: DEBUG
