apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: services
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
  selector:
    app: backend-service
