apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: infrastructure
spec:
  interval: 10m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
