name: Backend Server

on:
  push:
    paths:
      - 'backend-server/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: go build -v ./... -o backend-server
        working-directory: ./backend-server/

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.repository_owner }}/seclab-backend-server:latest
          context: ./backend-service/
